version: '3'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: strava-feedme-ecs-strava-feedme-staging
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web